사용 예시)
고객이라는 테이블을 만들어 볼 것.
  CREATE TABLE CUSTOMER(
    VIP_ID  CHAR(4) PRIMARY KEY,
    VIP_NAME VARCHAR2 (50) NOT NULL,
    VIP_ADDR VARCHAR2 (200),
    VIP_TEL_NUM VARCHAR2 (30)
);    
    CREATE TABLE GOODS(
    GID VARCHAR2(10) PRIMARY KEY,
    GOODS_NAME VARCHAR2 (30),
    GOODS_PRICE NUMBER (7) DEFAULT 0
);

